compile_with_test_sim0:
  script:
    - source ci/setup_ws.sh
    - catkin_make
    - catkin_make run_tests -j 1
    - catkin_test_results --verbose
    - catkin_test_results
    - tug_static_code_checking_helper/scripts/analyze.sh
  tags:
    - sim0
  except:
    - ci

compile_with_test_sim3:
  script:
    - source ci/setup_ws.sh
    - catkin_make
    - catkin_make run_tests -j 1
    - catkin_test_results --verbose
    - catkin_test_results
  tags:
    - sim3
  except:
    - ci
