device_drivers:
    first_device_driver:
        type: plugin_test_device_driver::FirstDeviceDriver

controlled_device_drivers:
    first_controlled_device_driver:
        type: plugin_test_controlled_device_driver::FirstControlledDeviceDriver

postprocessors:
    first_postprocessor:
        type: plugin_test_postprocessor::FirstPostprocessor

preprocessors:
    first_preprocessor:
        type: plugin_test_preprocessor::FirstPreprocessor

